### ISSUE TITLE
Git ignore file

### ISSUE THREAD

**Issue by craigsapp** [benory/1520s-project-scores#1]
There are files in the repository named:  `.DS_Store`.   These are unwanted files that are used by MacOS to cache file icons for viewing in the Finder.

You should create a file in the base directory of the repository called `.gitignore` and place that filename as the contents.   This will prevent any new `.DS_Store` files from being added to the repository.  You should then delete all existing `.DS_Store` files from the repository by running these commands from the base directory of the repository in a terminal:

```bash
rm -f .DS_Store
rm -f */.DS_Store
rm -f */*/.DS_Store
rm -f */*/*/.DS_Store
rm -f */*/*/*/.DS_Store
```

That should be enough commands to delete all of them (the last two commands or so should complain that there were no files to delete; otherwise, you should continue with the pattern.

**Comment by benory** [comment]
Thanks, @craigsapp! This should be resolved now.
