### ISSUE TITLE
Capitalization in directory names.

### ISSUE THREAD

**Issue by craigsapp** [benory/1520s-project-scores#2]
Here is a very minor point to consider:   

Note that the filenames use capitalization:

<img width="487" alt="Screen Shot 2022-02-07 at 7 14 13 PM" src="https://user-images.githubusercontent.com/3487289/152911287-037a3a46-21ad-4a04-8781-f7928af7053b.png">

But directory in which they are located start with the same letters in lower case:

"Bau1002a..." compared to "bau" for the directory name.   It seems more elegant to keep them both in the same case. (JRP does uppercase for both).

In the future for creating a website, it is more convenient to keep the letter cases consistent so that there is less debugging to do.

**Comment by craigsapp** [comment]
Another thought: This would help to distinguish from non-composer directory names that have three letters, such as `pdf`, `xml`, `sib`, etc for some sort of automated processing (but this should not be a real problem since such directories and composer directories are not being mixed together).

**Comment by benory** [comment]
Thanks, Craig! Unfortunately, git does not seem to be case sensitive, so even though I've updated the directories locally, I can't seem to push them easily. Do you have an easy solution for this?

**Comment by craigsapp** [comment]
I think the problem is your operating system -- MacOS has a file system that can ignore letter cases (linux and other unix file systems do not have this).  So to rename the files on a Mac requires two steps:

```bash
mv abc temp
mv temp Abc
```

You can still type `cd abc` on MacOS since it does not care about the case.

The more proper way of working with git is to move within git so that the files are not copied in the repository but rather moved:

```bash
git mv abc temp
git mv temp Abc
```

Using this system, the repository will not increase in size, but using mv outside of git will cause git to delete the old directory files and create new directory files within its storage system (doubling the size of the repository and losing the edit history for the new files).

**Comment by benory** [comment]
Thanks, Craig. I've now capitalized all the folder names. Does this look good to you now?

**Comment by benory** [comment]
@craigsapp good to go with the folder names?

**Comment by craigsapp** [comment]
Looks good.
