### ISSUE TITLE
Mensural Sign for Cut-Circle over 3

### ISSUE THREAD

**Issue by benory** [benory/1520s-project-scores#3]
Can we implement the mensural sign "Cut-Circle over 3"? 

The issue was previously raised here: https://github.com/rism-digital/verovio/issues/3525

**Comment by craigsapp** [comment]
Also added issue https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/873 to keep it in mind.

**Comment by craigsapp** [comment]
You can remind @lpugin about issue https://github.com/rism-digital/verovio/issues/3525 (which this message is designed to do 😜 ).

**Comment by craigsapp** [comment]
Should now be possible:

```tsv
**kern
*clefC3
*M2/1
*met(O|/3)
=
0.c
=
*-
```

<img width="537" alt="Screenshot 2024-09-27 at 12 01 37 PM" src="https://github.com/user-attachments/assets/c82bfee2-8cf8-4725-bf47-873a72da565f">

(in about 20 minutes after verovio is compiled for online use in VHV.)

**Comment by benory** [comment]
This is absolutely fantastic! Thanks @craigsapp for so quickly implementing this. I've updated all of my scores accordingly.
