### ISSUE TITLE
Hide Dot in Score

### ISSUE THREAD

**Issue by benory** [benory/1520s-project-scores#5]
For Wil3041, at measures 23–24, I have notated the tied breves in the Superius as "[0B" and "0.B]" which produces a dotted breve. Since the Superius is not yet in sesquialtera, I want to use "0B]" alone, but VHV does not like this solution. What should I do to omit the dot?

<img width="464" alt="Screenshot 2024-01-24 at 07 46 52" src="https://github.com/benory/1520s-project-scores/assets/74871483/3dac64ec-49df-4e98-ab97-29bc7f3569ae">

**Comment by craigsapp** [comment]
Like this:

<img width="600" alt="Screenshot 2024-01-24 at 09 12 12" src="https://github.com/benory/1520s-project-scores/assets/3487289/b2c7d6e1-a131-4fde-8ef7-2e043acf32bb">

[View in VHV](https://verovio.humdrum.org?t=KiprZXJuCipNMy8xCiptZXQoQ3wpCipjbGVmQzMKPQpbMGMuCj0KIUxPOk46dmlzPTAKMC5jXQo9CiotCg==)

For proper performance rendering there will be a better way of encoding: Music in 3 mensuration can be more properly encoded as triplets, and then use `*Xtuplet` to prevent display of tuplet brackets, and `*tuplet` if you need to show tuplet brackets again.

| note | encoding |
| --- | --- |
| triplet whole note | `3%2` |
| triplet breve note | `4%3` |

`3%2` means the note is 2/3rds of a whole note (or a whole note is 3/2 of a triplet whole note).

An intermediate method to avoid changing a lot of rhythms is to use triplet encoding method when not all parts have entered 3 mensuration.   When they all are in 3, add line:

```
!!primary-mensuration: 3
```

And encode the 3 mensuration notes as they currently are (as duple notes).

**Comment by benory** [comment]
Great. I've adjusted Wil3041.
