### ISSUE TITLE
Automatic Generation of Analysis Plots

### ISSUE THREAD

**Issue by benory** [benory/1520s-project-scores#6]
Can we get the data server to automatically generate the analysis plots once a new music score is added to 1520s Scores? I uploaded [this score](https://1520s-project.org/work/?id=Ver3002) yesterday morning, but it does not seem to have generated the plots yet. Since I highlight newly added works on the website, it would be good for the various analyses to appear fairly quickly thereafter.

**Comment by craigsapp** [comment]
The plan is that I would run a script daily to generate plots for new scores.   The data server is not 100% setup to do that yet, but I can get that running in a week or two.  For now you can complain when you want the plots to be generated.   I will start the script now and the plots should be available within an hour at the most.

**Comment by craigsapp** [comment]
I got distracted, but now the plots are online for the newest two scores.

**Comment by craigsapp** [comment]
<img width="1048" alt="Screenshot 2024-01-24 at 23 30 50" src="https://github.com/benory/1520s-project-scores/assets/3487289/a9a2617b-d2d1-4690-8036-64ee11735e19">
